myfm/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views
from landing import views

urlpatterns = [
    path('', views.home_view, name='home'),  # Main Landing Page
    path('app-mcp/', admin.site.urls),
    path('join/', user_views.register, name='join'),  # Register Page
    path('shows/', include('shows.url')),  # Shows Apps Urls
    path('users/', include('users.url')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),  # Login Page
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout')  # Logout Page
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/models.py
from django.db import models

# Create your models here.

pods/models.py
from django.db import models
from django.db.models.signals import pre_save
from myfm.utils import unique_sug_generator
from django.conf import settings


class PodShow(models.Model):
    pod_shw_title = models.CharField(max_length=250)
    pod_shw_icon = models.FileField()
    pod_shw_host = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.SET(1))
    slug = models.SlugField(unique=True)
    pod_shw_desc = models.CharField(max_length=1000)


def slug_save(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_sug_generator(instance, instance.pod_shw_title, instance.slug)


pre_save.connect(slug_save, sender=PodShow)


class PodEpisode(models.Model):
    pod_ep_title = models.CharField(max_length=250)
    pod_ep_show = models.ForeignKey(PodShow, on_delete=models.CASCADE)
    pod_ep_file = models.FileField()
    pod_ep_desc = models.CharField(max_length=1000)
    pod_ep_release = models.DateField(blank=True, null=True, verbose_name="Release Date")
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.pod_ep_show + ' : ' + self.pod_ep_title


def slug_save(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_sug_generator(instance, instance.pod_ep_title, instance.slug)


pre_save.connect(slug_save, sender=PodEpisode)

shows/models.py
from django.db import models
from django.db.models.signals import pre_save
from myfm.utils import unique_sug_generator


class Station(models.Model):
    st_name = models.CharField(max_length=250)
    slug = models.SlugField(unique=True)
    st_icon = models.FileField()
    st_freq = models.CharField(max_length=100)
    st_live = models.CharField(max_length=1000)
    st_tagline = models.CharField(max_length=100)

    def __str__(self):
        return self.st_name + ' - ' + self.st_freq


def slug_save(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_sug_generator(instance, instance.st_name, instance.slug)


pre_save.connect(slug_save, sender=Station)


# def get_absolute_url(self):
#     return reverse("shows:stations", kwargs={"slug": self.slug})


class Show(models.Model):
    shw_title = models.CharField(max_length=250)
    slug = models.SlugField(unique=True)
    shw_hosts = models.CharField(max_length=250)
    shw_icon = models.FileField()
    shw_desc = models.CharField(max_length=1000, null='false')
    shw_station = models.ForeignKey(Station, on_delete=models.CASCADE)
    shw_live_on_time = models.TimeField(blank=True, null=True)
    shw_live_off_time = models.TimeField(blank=True, null=True)
    shw_days = models.CharField(max_length=250)

    def __str__(self):
        return self.shw_title + ' with - ' + self.shw_hosts


def slug_save(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_sug_generator(instance, instance.shw_title, instance.slug)


pre_save.connect(slug_save, sender=Show)


class Episode(models.Model):
    ep_show = models.ForeignKey(Show, on_delete=models.CASCADE)
    ep_title = models.CharField(max_length=250)
    ep_file = models.FileField()
    ep_release_date = models.DateField(blank=True, null=True, verbose_name="Release Date")

    def __str__(self):
        return self.ep_title

shows/forms.py
from django.contrib.auth.models import User
from django import forms

users/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

landing/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse
from django.template import loader, RequestContext


def home_view(request):
    context = {'home': 'landing'}
    return render_to_response('landing/home.html', context)

pods/views.py
from django.shortcuts import render

# Create your views here.

shows/views.py
from django.views import generic
from .models import Station, Show, Episode
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render


# Shows List View
class IndexView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'shows/index.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['all_shows'] = Show.objects.all()
        context_data['all_radio'] = Station.objects.all()
        return context_data


# Show Details View
class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Show
    template_name = 'shows/details.html'

    def get_queryset(self):
        return Show.objects.all()


# Radio List View
class RadioView(LoginRequiredMixin, generic.ListView):
    template_name = 'shows/radio.html'
    context_object_name = 'all_radio'

    def get_queryset(self):
        return Station.objects.all()


# Radio Station Detail View
class StationView(LoginRequiredMixin, generic.DetailView):
    model = Station
    template_name = 'shows/station.html'

    def get_queryset(self):
        return Station.objects.all()

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm


# User Registration Form.
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'{username}, your account has been created. You can now login!')
            return redirect('login')

    else:
        form = UserRegisterForm()

    return render(request, 'users/register.html', {'form': form})

landing/templates/landing/home-base.html
<!--
my.FM Base template
Built by A.Kimani
Base built by w3Schools
-->

{% load staticfiles %}
<!DOCTYPE HTML>
<html>
<head>
    <title>{% block title %}my.FM: Keep Calm and Listen :){% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'shows/images/icon.png' %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="my.FM" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <link href="{% static 'shows/css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
    <link href="{% static 'shows/css/style.css' %}" rel='stylesheet' type='text/css' />
    <link href="{% static 'shows/css/font-awesome.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'shows/css/icon-font.css' %}" type='text/css' />
    <script src="{% static 'shows/js/jquery-2.1.4.js' %}"></script>
    <style>
        #bar {
            position:absolute;
            width:0%;
            height:5px;
            top:0;
            left:0;
            z-index:9;
            border-radius: 3px;
            background:#00ace5;
        }
    </style>
    <script>
        var pg=0; //progress bar width initially
        document.onreadystatechange = function()
        {
            if(document.readyState=="interactive")
            {
                var allElem = $("*");
                var length = allElem.length;
                for(var i=0;i<length;i++) {
                    set_elem(allElem[i],length);
                }
            }
        }

        function  set_elem(elem,total) {
            var percent_inc = 100 / total; //equally divide 100 among all elements

            //if element is loaded
            if($(elem).length==1) {
                $('#bar').animate({width:pg+percent_inc+"%"},10,function(){
                    if(document.getElementById("bar").style.width=="100%") {
                        //hide the bar
                        $('#bar').fadeOut(350);
                    }
                });
                //update the previous width value
                pg = pg+percent_inc;
            }
        }
    </script>
</head>

<body class="sticky-header left-side-collapsed" style="margin-left: -70px"  onload="initMap()">
<section>

    <div class="main-content">
        <!-- header-starts -->
        <div class="header-section" style="margin-left: -50px">
            <div id="bar"></div>
            <!--toggle button start-->
            <a href="{% url 'home' %}"><img src="/static/shows/images/logo_vert.png" style="width: 60px; height: 50px; margin-left: 20px"></a>

            <!--toggle button end-->
            <div class="clearfix"> </div>
            <div class="menu-right">
                <div class="profile_details">
                    <div class="col-md-4">
                    </div>
                    <div class="col-md-4">
                    </div>
                    <div class="col-md-4" style="margin-top: -40px; margin-bottom: 5px">
                        <div class="col-md-2" style="margin-left: 20px;float: right">
                            <a href="{% url 'login' %}">
                                <button class="btn btn-danger" style="float: right;">
                                    LogIn
                                </button>
                            </a>
                        </div>
                        <div class="col-md-2" style="margin-left: 20px;float: right">
                            <a href="{% url 'join' %}">
                                <button class="btn btn-primary" style="float: right;">
                                    Join Us!
                                </button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        {% block body %}

        {% endblock %}

        <div class="clearfix"></div>

        <!--
        <div class="footer">
            <div class="footer-grid">
                <h3>Navigation</h3>
                <ul class="list1">
                  <li><a href="index.html">Home</a></li>
                  <li><a href="radio.html">All Songs</a></li>
                  <li><a href="browse.html">Albums</a></li>
                  <li><a href="radio.html">New Collections</a></li>
                  <li><a href="blog.html">Blog</a></li>
                  <li><a href="contact.html">Contact</a></li>
                </ul>
            </div>
            <div class="footer-grid">
                <h3>Our Account</h3>
                <ul class="list1">
                  <li><a href="#" data-toggle="modal" data-target="#myModal5">Your Account</a></li>
                  <li><a href="#">Personal information</a></li>
                  <li><a href="#">Addresses</a></li>
                  <li><a href="#">Discount</a></li>
                  <li><a href="#">Orders history</a></li>
                  <li><a href="#">Addresses</a></li>
                  <li><a href="#">Search Terms</a></li>
                </ul>
            </div>
            <div class="footer-grid">
                <h3>Our Support</h3>
                <ul class="list1">
                  <li><a href="contact.html">Site Map</a></li>
                  <li><a href="#">Search Terms</a></li>
                  <li><a href="#">Advanced Search</a></li>
                  <li><a href="#">Mobile</a></li>
                  <li><a href="contact.html">Contact Us</a></li>
                  <li><a href="#">Mobile</a></li>
                  <li><a href="#">Addresses</a></li>
                </ul>
              </div>
                  <div class="footer-grid">
                    <h3>Newsletter</h3>
                    <p class="footer_desc">Nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat</p>
                    <div class="search_footer">
                     <form>
                       <input type="text" placeholder="Email...." required="">
                      <input type="submit" value="Submit">
                      </form>
                    </div>
                 </div>
                 <div class="footer-grid footer-grid_last">
                    <h3>About Us</h3>
                    <p class="footer_desc">Diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat enim ad minim veniam,.</p>
                    <p class="f_text">Phone:  &nbsp;&nbsp;&nbsp;00-250-2131</p>
                    <p class="email">Email : &nbsp;<span><a href="mailto:mail@example.com">info(at)mailing.com</a></span></p>
                 </div>
                 <div class="clearfix"> </div>
                </div>
                -->

        <!--footer section start-->
        <footer style="margin-left: 18px;float: bottom;">
            <p>&copy 2019 my.FM  All Rights Reserved.</p>
        </footer>
        <!--footer section end-->
    </div>
</section>

<script src="{% static 'shows/js/jquery.nicescroll.js' %}"></script>
<script src="{% static 'shows/js/scripts.js' %}"></script>
<script src="{% static 'shows/js/bootstrap.js' %}"></script>
<input type="hidden" id="progress_width" value="0">
</body>
</html>

shows/templates/shows/details.html
{% extends 'shows/base.html' %} 
{% load staticfiles %} 

{% block title %}my.FM: {{ show }}{% endblock %} 

{% block body %}
    <!-- Start Of Body Block Content -->
    <div id="page-wrapper">

        <div class="music-left" style="width: 33%;">
            <!-- Img Box -->
            <div class="video-main">
                <div id="jp_container_1" class="jp-video jp-video-270p" style="padding-left: 30px; padding-top: 30px;">
                    <div id="jquery_jplayer_1" class="jp-jplayer" style="width: 480px; height: 270px;">
                        <img src="{{ show.shw_icon.url }}" style="width: 270px; height: 270px; border: 1px;border-radius: 10px !important; border-style: solid; border-color: #000; display: inline;">
                    </div>
                </div>
            </div>
            <!-- Img Box End -->
        </div>

        <div class="music-right">
            <!-- Show More Info -->
            <div class=".col-md-12">
                <h4 style="margin-bottom: -5px; color: #adb5bd;">SHOW</h4>
                <h1 style="text-align: left; color: #b10404;"><b> {{ show.shw_title }} </b></h1>
                <p style="text-align: left;">By: {{ show.shw_hosts }}</p>
                <div class="clearfix"> </div>
            </div>
            <!-- More Info End -->

            <!-- Separator -->
            <div style="display: inline-block; height: 2px; width: 35px; background: #252525;"></div>
            <!-- Separator End -->

            <div class=".col-md-12">
                <p style="text-align: left;"><span style="color: #00ace5">Station: </span>{{ show.shw_station }}</p>
                <p style="text-align: left;"><span style="color: #00ace5">Live from: </span>{{ show.shw_live_on_time }} <span style="color: #00ace5">to</span> {{ show.shw_live_off_time}}</p>
            </div>

            <!-- Separator -->
            <div style="display: inline-block; height: 2px; width: 35px; background: #252525;"></div>
            <!-- Separator End -->

        </div>

        <div class="clearfix"> </div><br>

        <div class="col-md-2">
        </div>

        <div class="col-md-8">
            <!-- About Show -->
            <div>
                <h4 style="text-align: center"><b>About this Show:</b></h4>
                <p style="text-align: center">{{ show.shw_desc}}</p>
            </div>
            <!-- About Show End -->

            <div class="clearfix"> </div><br>

            <!-- Separator -->
            <div style="display: inline-block; height: 2px; width: 100%; background: #252525;"></div>
            <!-- Separator End -->

            <h4 style="text-align: center"><b>Show Episodes:</b></h4>

            <div class="clearfix"> </div><br>

            <!-- HTML5 Audio Player -->
            <audio controls id="audioPlayer" style="width: 100%">
                    <source src="">
                </audio>
            <!-- HTML5 Audio Player End -->

            <!-- Episodes List -->
            <div class="media response-info">
                {% for episode in show.episode_set.all %}
                <div class="media-body response-text-left">
                    <style>
                        #playlist {
                            list-style: none;
                        }
                        
                        #playlist .current-song a {
                            color: #00ace5;
                        }
                    </style>
                    <ul id="playlist" class="#playlist">
                        <li class="current-song">
                            <a href="{{ episode.ep_file.url }}">
                                <p style="border-radius: 30px !important; border-top: solid 1px #0b0b0b; border-bottom: solid 1px #b10404; padding: 10px; padding-left: 20px; margin-top: 10px">{{ episode.ep_title }} -- Released: {{ episode.ep_release_date }}</p>
                            </a>
                        </li>
                    </ul>
                    <script>
                        audioPlayer();

                        function audioPlayer() {
                            var currentSong = 0;
                            $("#audioPlayer")[0].src = $("#playlist li a")[0];
                            $("#audioPlayer")[0].play();
                            $("#playlist li a").click(function(e) {
                                e.preventDefault();
                                $("#audioPlayer")[0].src = this;
                                $("#audioPlayer")[0].play();
                                $("#plalist li").removeClass("current-song");
                                currentSong = $(this).parent().index();
                                $(this).parent.addClass("current-song");
                            });
                            $("#audioPlayer")[0].addEventListener("ended", function() {
                                currentSong++;
                                if (currentSong == $("#playlist li a").length)
                                    currentSong = 0;
                                $("#playlist li").removeClass("current-song");
                            });
                        }
                    </script>
                </div>
                <div class="clearfix"> </div>
                {% endfor %}
            </div>
            <!-- Episodes List End -->
        </div>
        <div class="clearfix"> </div>
        <div class="review-slider">

            <div class="tittle-head">
                <h3 class="tittle">Featured Shows </h3>
                <div class="clearfix"> </div>
            </div>

            {% for show in all_shows %}
            <div class="col-md-3">
                <a href="{% url 'shows:show' show.slug %}"><img src="{{ show.shw_icon.url }}" style="width: 253px; height: 253px; border-radius: 15px !important; border-top: solid 1px #0b0b0b; border-bottom: solid 1px #b10404"></a>
                <a class="sing" href="{% url 'shows:show' show.slug %}" style="color: #b10404; text-align: center">{{ show }}</a>
                <div class="clearfix"></div>
                <hr>
            </div>
            {% endfor %}

            <!-- <ul id="flexiselDemo1">
                {% for show in show.show_set.all %}
                <li>
                    <a href="{% url 'shows:show' show.slug %}"><img src="{{ show.shw_icon.url }}"></a>
                    <div class="slide-title">
                        <h4><a class="sing" href="{% url 'shows:show' show.slug %}">{{ show.shw_title }}</a></h4>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <script type="text/javascript">
                $(window).load(function() {

                    $("#flexiselDemo1").flexisel({
                        visibleItems: 5,
                        animationSpeed: 1000,
                        autoPlay: true,
                        autoPlaySpeed: 3000,
                        pauseOnHover: false,
                        enableResponsiveBreakpoints: true,
                        responsiveBreakpoints: {
                            portrait: {
                                changePoint: 480,
                                visibleItems: 2
                            },
                            landscape: {
                                changePoint: 640,
                                visibleItems: 3
                            },
                            tablet: {
                                changePoint: 800,
                                visibleItems: 4
                            }
                        }
                    });
                });
            </script> -->
            <script type="text/javascript" src="{% static 'shows/js/jquery.flexisel.js' %}"></script>
        </div>

    </div>

{% endblock %}

shows/templates/shows/index.html
{% extends 'shows/base.html' %} 
{% load staticfiles %} 
{% block body %}
<!-- Main Body -->
<div id="page-wrapper">
    <div class="inner-content">
        <!--Left section-->
        <div class="music-left">

            <!--banner-section-->
            <div class="banner-section">
                <div class="banner">
                    <div class="callbacks_container">
                        <ul class="rslides callbacks callbacks1" id="slider4">
                            <li>
                                <div class="banner-img">
                                    <img src="{% static 'shows/images/banner1.png'%}" class="img-responsive" alt="">
                                </div>
                                <div class="banner-info" style="position: absolute;right: 1px;text-align: right;margin-right: 150px">
                                    <a class="trend" href="">WELCOME</a>
                                </div>

                            </li>
                            <li>
                                <div class="banner-img">
                                    <img src="{% static 'shows/images/radio2.png'%}" class="img-responsive" alt="">
                                </div>
                                <div class="banner-info">
                                    <a class="trend" href="">NOW</a>
                                    <h3>Kill the FOMO</h3>
                                    <p>Don't miss out on your fav <span>Show :)</span></p>
                                </div>


                            </li>
                            <li>
                                <div class="banner-img">
                                    <img src="{% static 'shows/images/mic.jpg'%}" class="img-responsive" alt="">
                                </div>
                                <div class="banner-info">
                                    <a class="trend" href="">WHAT'S ON YOUR MIND?</a>
                                    <h3>Let's give your thoughts a voice</h3>
                                    <p style="color: #0b0b0b">Speak your mind and let your friends <span style="color: #00ace5"> Hear what you have to say!</span></p>
                                </div>

                                <!-- /w3layouts-agileits -->
                            </li>
                        </ul>
                    </div>
                    <!--banner-->
                    <script src="{% static 'shows/js/responsiveslides.min.js' %}"></script>
                    <script>
                        // You can also use "$(window).load(function() {"
                        $(function() {
                            // Slideshow 4
                            $("#slider4").responsiveSlides({
                                auto: true,
                                pager: false,
                                nav: true,
                                speed: 500,
                                namespace: "callbacks",
                                before: function() {
                                    $('.events').append("<li>before event fired.</li>");
                                },
                                after: function() {
                                    $('.events').append("<li>after event fired.</li>");
                                }
                            });

                        });
                    </script>
                    <div class="clearfix"> </div>
                </div>
            </div>

            <div class="clearfix"></div>
            <!--//End-banner-->

            <!-- Shows Section -->
            <div class="browse" style="margin-top: 50px">
                <div class="tittle-head">
                    <h3 class="tittle" style="font-size: 20px">Shows: <span class="new"> All</span></h3>
                    <h4 class="tittle two" style="margin-top: -50px;font-size: 18px">See all</h4>
                </div>
                {% for show in all_shows %}
                <div class="col-md-3" style="margin-right: 10px">
                    <a href="{% url 'shows:show' show.slug %}"><img src="{{ show.shw_icon.url }}" style="width: 190px; height: 190px; border-radius: 15px !important; border-top: solid 1px #0b0b0b; border-bottom: solid 1px #b10404"></a>
                    <a class="sing" href="{% url 'shows:show' show.slug %}">{{ show.shw_title }}</a>
                </div>
                {% endfor %}
            </div>
            <!--Shows section end-->

            <div class="clearfix"></div>
            <hr>


            <div class="browse">
                <img src="{% static 'shows/images/expe.jpg' %}" style="width:100%;height: 100%; border-radius: 15px !important;">
            </div>

            <!--Stations section-->
            <div class="browse">
                <div class="tittle-head">
                    <h3 class="tittle" style="font-size: 20px">Stations: <span class="new"> All</span></h3>
                    <a href="{% url 'shows:station' %}">
                        <h4 class="tittle two" style="margin-top: -50px;font-size: 18px">See all</h4>
                    </a>
                </div>
                {% for station in all_radio %}
                <div class="col-md-3" style="margin-right: 10px">
                    <a href="{% url 'shows:stations' station.slug %}"><img src="{{ station.st_icon.url }}" style="width: 190px; height: 190px; border-radius: 15px !important; border-top: solid 1px #0b0b0b; border-bottom: solid 1px #b10404"></a>
                    <a class="sing" href="{% url 'shows:stations' station.slug %}">{{ station }}</a>
                    <div class="clearfix"></div>
                    <hr>
                </div>
                {% endfor %}
            </div>
            <!--Stations section end-->
        </div>
        <!--Left section end-->

        <!--Right Section-->
        <div class="music-right">
            <div class="video-main">
                <img src="{% static 'shows/images/old.jpg' %}" style="width:100%;height: 100%; border-radius: 15px !important;">
            </div>
            <div class="apps">
                <h3 class="hd-tittle">MyFM now available in</h3>
                <div class="banner-button">
                    <a href="#"><img src="{% static 'shows/images/1.png' %}" alt=""></a>
                </div>
                <div class="banner-button green-button">
                    <a href="#"><img src="{% static 'shows/images/2.png' %}"" alt=""></a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <!--Right section end-->
    </div>
</div>
{% endblock %}

shows/templates/shows/station.html
{% extends 'shows/base.html' %}
{% load staticfiles %}

{% block title %}my.FM: {{ station }}{% endblock %}

{% block body %}
    <!-- Main Boy -->
    <div id="page-wrapper">
        <div class="inner-content">
          <div class="music-browse">
                <div class="browse">
                    <div class="tittle-head two" style="background-color: #f4f4f4;">
                        <div class="col-md-4 grid_box1" style="position: center;">
                            <img src="{{ station.st_icon.url }}" style="width: 200px; height: 200px; position: center; margin-top: -20px">
                        </div>
                        <br>
                        <h4 style="margin-bottom: -5px; color: #adb5bd; margin-left: 20px">STATION</h4>
                        <h1 style="text-align: left; color: #b10404; margin-bottom: -5px; margin-left: 10px"><b>{{ station.st_name }}</b></h1>
                        <h4 style="text-align: left; color: #1e171d; margin-bottom: -10px; margin-left: 20px">{{ station.st_tagline }}</h4>
                        <h4 style="text-align: left; color: #1e171d; margin-bottom: -5px; margin-left: 20px"><b>{{ station.st_freq }}</b></h4>
                        <div class="clearfix"> </div>
                    </div>

                    <div class="row">
                        <div class="col-md-3 grid_box1">
                        </div>
                        <div class="col-md-6 grid_box1">
                        <div class="clearfix"> </div><br>
                            <audio controls id="audioPlayer" style="width: 100%">
                                <source src="{{ station.st_live }}">
                            </audio>
                            <h4 style="text-align: center; color: #00ace5;"><b>LISTEN LIVE</b></h4>
                        </div>
                        <div class="col-md-3">
                        </div>
                        <div class="clearfix"> </div><hr>
                    </div>

                    <h3 class="tittle" style="text-align: center;">OUR SHOWS:<span class="new">All</span></h3><br>
                    {% for show in station.show_set.all %}
                        <div class="col-md-3">
                            <a href="{% url 'shows:show' show.slug %}"><img src="{{ show.shw_icon.url }}" style="width: 253px; height: 253px; border-radius: 15px !important; border-top: solid 1px #0b0b0b; border-bottom: solid 1px #b10404"></a>
                            <a class="sing" href="{% url 'shows:show' show.slug %}" style="color: #b10404; text-align: center">{{ show }}</a>
                        <div class="clearfix"></div><hr>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}
           